spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost/db_med_api
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Vizualizar por consola consultar SQL de manera legible para hacer pruebas
spring.jpa.show-sql=true
spring.jpa.propierties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=12345678